services:
  - type: web
    name: api-reservas
    env: docker
    plan: free
    repo: https://github.com/pipp3/roomyAPI
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        value: https://roomy.onrender.com
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://roomy.onrender.com/auth/google/callback
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_COOKIE_NAME
        value: token
      - key: API_URL
        value: https://roomy.onrender.com
